config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :ordems, :partes, :equipes, :mecanicos, :servicos

  resources :clientes do
    resources :veiculos
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "ordems#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many :veiculos, dependent: :destroy

  validates :nome, presence: true
  validates :endereco, presence: true
  validates :telefone, presence: true
end

app/models/equipe.rb
class Equipe < ApplicationRecord
  has_many :mecanicos

  validates :nome, presence: true

  def numIntegrantes?
    Mecanico.where(equipe_id:id).count
  end
end

app/models/mecanico.rb
class Mecanico < ApplicationRecord
  validates :nome, presence: true
  validates :endereco, presence: true
  validates :especialidade, presence: true
end

app/models/ordem.rb
class Ordem < ApplicationRecord

  STATUS_VALIDOS = ['Aberto', 'Em andamento', 'Pausado', 'Finalizado']

  validates :problema, presence: true
  validates :dataEmissao, presence: true
  validates :veiculo_id, presence: true
  validates :status, presence: true, inclusion: { in: STATUS_VALIDOS }



end

app/models/ordems_partes.rb
class Ordems_partes < ApplicationRecord
  belongs_to :ordem, :parte
end

app/models/ordems_servicos.rb
class Ordems_servicos < ApplicationRecord
  belongs_to :servico, :ordem
end

app/models/parte.rb
class Parte < ApplicationRecord

  validates :nome, presence: true
  validates :descricao, presence: true
  validates :valor, presence: true



end

app/models/servico.rb
class Servico < ApplicationRecord

  validates :nome, presence: true
  validates :descricao, presence: true
  validates :valor, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
  belongs_to :cliente

  validates :placa, presence: true
  validates :marca, presence: true
  validates :modelo, presence: true
  validates :ano, presence: true
  validates :cor, presence: true
  validates :descricao, presence: true
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :authenticate_user!
  def index
    @clientes = Cliente.all
  end

  def new
    @cliente = Cliente.new
  end

  def create
    @cliente = Cliente.new(cliente_params)

    if @cliente.save
      redirect_to @cliente
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @cliente = Cliente.find(params[:id])
    @veiculos = Veiculo.where(cliente_id: params[:id])
  end

  def edit
    @cliente = Cliente.find(params[:id])
  end

  def update
    @cliente = Cliente.find(params[:id])

    if @cliente.update(ordem_params)
      redirect_to @cliente
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def cliente_params
      params.require(:cliente).permit(:nome, :endereco, :telefone)
    end
end

app/controllers/equipes_controller.rb
class EquipesController < ApplicationController
  before_action :authenticate_user!
  def index
    @equipes = Equipe.all
  end

  def show
    @equipe = Equipe.find(params[:id])
    @integrantes = Mecanico.all
  end

  def new
    @equipe = Equipe.new
  end

  def create
    @equipe = Equipe.new(equipe_params)

    if @equipe.save
      redirect_to @equipe
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @integrantes = params[:integrantes]
    @integrantes.each do |integrante|
      if(integrante != "")
        @mecanico = Mecanico.find(integrante)
        @mecanico.equipe_id = params[:equipe_id]
        @mecanico.save
      end
    end
    redirect_to equipe_path(params[:equipe_id])
  end

  private
    def equipe_params
      params.require(:equipe).permit(:nome)
    end


end

app/controllers/ordems_controller.rb
class OrdemsController < ApplicationController
  before_action :authenticate_user!
  before_action :carregarDependencias, only: [:new, :index, :edit]

  def index
    @ordems = Ordem.all
  end

  def show
    @ordem = Ordem.find(params[:id])
    @veiculo = Veiculo.find(@ordem.veiculo_id)
    @equipe = Equipe.find(@ordem.equipe_id)
    @partes = []
    @servicos = []
  end

  def new
    @novo = true
    @ordem = Ordem.new
  end

  def create

    @ordem = Ordem.new(ordem_params)

    if @ordem.save
      redirect_to @ordem
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @novo = false
    @ordem = Ordem.find(params[:id])
  end

  def update
    @ordem = Ordem.find(params[:id])

    if @ordem.update(ordem_params)
      redirect_to @ordem
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def ordem_params
      params.require(:ordem).permit(:dataEmissao, :problema, :equipe_id, :status, :veiculo_id, :partes, :servicos)
    end

    def carregarDependencias
      @veiculos = Veiculo.all
      @equipes = Equipe.all
      @partes = Parte.all
      @servicos = Servico.all
    end
end

app/controllers/partes_controller.rb
class PartesController < ApplicationController
  before_action :authenticate_user!
  def index
    @partes = Parte.all
  end

  def show
    @parte = Parte.find(params[:id])
  end

  def new
    @parte = Parte.new
  end

  def create
    @parte = Parte.new(parte_params)

    if @parte.save
      redirect_to @parte
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @parte = Parte.find(params[:id])
  end

  def update
    @parte = Parte.find(params[:id])

    if @parte.update(ordem_params)
      redirect_to @parte
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def parte_params
      params.require(:parte).permit(:nome, :descricao, :modelo, :valor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/equipes_helper.rb
module EquipesHelper
end

app/helpers/mecanicos_helper.rb
module MecanicosHelper
end

app/helpers/ordems_helper.rb
module OrdemsHelper
end

app/helpers/partes_helper.rb
module PartesHelper
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/clientes/_form.html.erb
<%= form_with model: cliente, class:"col-10" do |form| %>
    <div>
        <%= form.label :nome, class:"form-label mt-2" %><br>
        <%= form.text_field :nome, class:"form-control" %>
        <% cliente.errors.full_messages_for(:nome).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :endereco, class:"form-label mt-2" %><br>
        <%= form.text_field :endereco, class:"form-control" %>
        <% cliente.errors.full_messages_for(:endereco).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :telefone, class:"form-label mt-2" %><br>
        <%= form.text_field :telefone, class:"form-control"  %>
        <% cliente.errors.full_messages_for(:telefone).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div class="mt-3">
        <%= form.submit %>
    </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editar Cliente</h1>

<%= render "form", cliente: @cliente %>

app/views/clientes/index.html.erb
<h1>Clientes</h1>

<%= link_to new_cliente_path, class: "text-decoration-none fs-4" do %>
    <div>
        <i class="bi bi-plus-circle"></i> Novo
    </div>
<% end %>

<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th class="col">#</th>
            <th class="col">Nome</th>
            <th class="col">Telefone</th>
            <th class="col">Endereço</th>
            <th class="col">Ações</th>
        </tr>
    </thead>
    <tbody>    
        <% @clientes.each do |cliente| %>
            <tr>
                <td><%= cliente.id %></td>
                <td><%= cliente.nome %></td>
                <td><%= cliente.telefone %></td>
                <td><%= cliente.endereco %></td>
                <td>
                    <%= link_to cliente, class: "text-decoration-none" do %>
                        <i class="bi bi-eye-fill fs-4 link-dark"></i>
                    <% end %>
                    <%= link_to edit_cliente_path(cliente), class: "text-decoration-none" do %>
                        <i class="bi bi-pen-fill fs-4 link-dark"></i>
                    <% end %>
                </td>
            </tr>
        <% end %>
        <hr>
    </tbody>
</table>

app/views/clientes/new.html.erb
<h1>Novo Cliente</h1>

<%= render "form", cliente: @cliente %>

app/views/clientes/show.html.erb
<%= link_to clientes_path, class: "mt-3 text-decoration-none fs-4" do %>
    <div>
        <i class="bi bi-arrow-return-left"></i> Voltar
    </div>
<% end %>

<h2 class="mt-2"><%= @cliente.nome %></h2>
<h5>Telefone: </h5>
<p><%= @cliente.telefone %></p>
<h5>Endereço: </h5>
<p><%= @cliente.endereco %></p>

<%= link_to new_cliente_veiculo_path(params[:id]), class: "text-decoration-none fs-4" do %>
    <div>
        <i class="bi bi-plus-circle"></i> Novo
    </div>
<% end %>

<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th class="col">#</th>
            <th class="col">Placa</th>
            <th class="col">Modelo</th>
            <th class="col">Ano</th>
            <th class="col">Ações</th>
        </tr>
    </thead>
    <tbody>    
        <% @veiculos.each do |veiculo| %>
            <tr>
                <td><%= veiculo.id %></td>
                <td><%= veiculo.placa %></td>
                <td><%= veiculo.modelo %></td>
                <td><%= veiculo.ano %></td>
                <td>
                    <%= link_to cliente_veiculo_path(cliente_id: @cliente, id: veiculo), class: "text-decoration-none" do %>
                        <i class="bi bi-eye-fill fs-4 link-dark"></i>
                    <% end %>
                    <%= link_to edit_cliente_veiculo_path(cliente_id: @cliente, id: veiculo), class: "text-decoration-none" do %>
                        <i class="bi bi-pen-fill fs-4 link-dark"></i>
                    <% end %>
                </td>
            </tr>
        <% end %>
        <hr>
    </tbody>
</table>

app/views/equipes/_form.html.erb
<%= form_with model: equipe, class:"col-10" do |form| %>
    <div>
        <%= form.label :nome, class:"form-label mt-2" %><br>
        <%= form.text_field :nome, class:"form-control" %>
        <% equipe.errors.full_messages_for(:nome).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div class="mt-3">
        <%= form.submit %>
    </div>
<% end %>

app/views/equipes/edit.html.erb
<h1>Editar equipe</h1>

<%= render "form", equipe: @equipe %>

app/views/equipes/index.html.erb
<h1>Equipes</h1>

<%= link_to new_equipe_path, class: "text-decoration-none fs-4" do %>
    <div>
        <i class="bi bi-plus-circle"></i> Novo
    </div>
<% end %>

<table class="table table-bordered table-hover table-striped mt-3">
    <thead>
        <tr>
            <th class="col">#</th>
            <th class="col">Nome</th>
            <th class="col">Nº integrantes</th>
            <th class="col">Ações</th>
        </tr>
    </thead>
    <tbody>
        <% @equipes.each do |equipe| %>
            <tr>
                <td><%= equipe.id %></td>
                <td><%= equipe.nome %></td>
                <td><%= equipe.numIntegrantes? %></td>
                <td>
                    <%= link_to equipe, class: "text-decoration-none" do %>
                        <i class="bi bi-eye-fill fs-4 link-dark"></i>
                    <% end %>
                    <%= link_to edit_equipe_path(equipe), class: "text-decoration-none" do %>
                        <i class="bi bi-pen-fill fs-4 link-dark"></i>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/equipes/new.html.erb
<h1>Nova equipe</h1>

<%= render "form", equipe: @equipe %>

app/views/equipes/show.html.erb
<%= link_to equipes_path, class: "mt-3 text-decoration-none fs-4" do %>
    <div>
        <i class="bi bi-arrow-return-left"></i> Voltar
    </div>
<% end %>

<h1><%= @equipe.nome %></h1>

<hr>

<h3>Integrantes</h3>

<ul>
    <% @integrantes.each do |integrante| %>
        <% if integrante.equipe_id == params[:id].to_i %>
            <li><%= integrante.nome %></li>
        <% end %>

    <% end %>
</ul>

<h5>Adicionar Integrante</h5>

<% mecanicos = Array.new %>
<% @integrantes.each do |i| %>
    <% unless i.equipe_id == params[:id].to_i %>
        <% mecanicos.push(i) %>
    <% end %>
<% end %>

<%= form_with method: :put, url: equipe_path(id: @equipe) do |form| %>
    <%= form.hidden_field :equipe_id, value: params[:id] %>
    <div>
        <%= form.collection_check_boxes :integrantes, mecanicos, :id, :nome %>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/ordems/_form.html.erb
<%= form_with model: ordem, class:"col-10" do |form| %>

    <div>
        <%= form.label :veiculo_id, class:"form-label" %><br>
        <%= form.collection_select :veiculo_id, @veiculos, :id, :placa, {}, {class:"input-placa form-control mx-5"} %>
        <% ordem.errors.full_messages_for(:veiculo_id).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :problema, class:"form-label mt-2" %><br>
        <%= form.text_area :problema, {class:"form-control"} %>
        <% ordem.errors.full_messages_for(:problema).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :equipe_id, class:"form-label mt-2" %><br>
        <%= form.collection_select :equipe_id, Equipe.all, :id, :nome, {}, {class:"input-equipe form-control"} %>
        <% ordem.errors.full_messages_for(:equipe_id).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    
    <div>
        <%= form.label :dataEmissao, "Data de Emissão", class:"form-label mt-2" %><br>
        <input type="date" id="ordem_dataEmissao" name="ordem[dataEmissao]" class="control-group" required>
        <% ordem.errors.full_messages_for(:dataEmissao).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :status, class:"form-label mt-2" %><br>
        <%= form.select :status, Ordem::STATUS_VALIDOS, {selected: 'Aberto'}, class:"form-select" %>
    </div>

    <% unless @novo %>
        <%= form.fields_for :ordems_partes do |f| %>
            <div>
                <%= f.label :parte_id, "Serviço", class:"form-label mt-2" %><br>
                <%= f.collection_select :parte_id, @partes, :id, :nome, {}, {class:"form-control"} %>
            </div>
        <% end %>
        <%= form.fields_for :ordems_partes do |f| %>
            <div>
                <%= f.label :parte_id, "Serviço", class:"form-label mt-2" %><br>
                <%= f.collection_select :parte_id, @partes, :id, :nome, {}, {class:"form-control"} %>
            </div>
        <% end %>
    <% end %>

    <div class="mt-3">
        <%= form.submit %>
    </div>
<% end %>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" />

<script>
    document.querySelector("#ordem_dataEmissao").valueAsDate = new Date();

    $(document).ready(function() {
        $('.input-placa').select2({
            theme: "bootstrap-5",
        });
    });
    $(document).ready(function() {
        $('.input-equipe').select2({
            theme: "bootstrap-5"
        });
    });
    $(document).ready(function() {
        $('.input-partes').select2({
            theme: "bootstrap-5"
        });
    });
    $(document).ready(function() {
        $('.input-servicos').select2({
            theme: "bootstrap-5"
        });
    });
</script>

app/views/ordems/edit.html.erb
<h1>Editar Ordem de Serviço</h1>

<%= render "form", ordem: @ordem %>

app/views/ordems/index.html.erb
<h1>Ordens de serviço</h1>

<%= link_to new_ordem_path, class: "text-decoration-none fs-4" do %>
    <div>
        <i class="bi bi-plus-circle"></i> Novo
    </div>
<% end %>

<table class="table table-bordered table-hover table-striped mt-3">
    <thead>
        <tr>
            <th class="col">#</th>
            <th class="col">Placa</th>
            <th class="col">Status</th>
            <th class="col">Equipe</th>
            <th class="col">Ações</th>
        </tr>
    </thead>
    <tbody>
        <% @ordems.each do |ordem| %>
            <tr>
                <td><%= ordem.id %></td>
                <td><%= @veiculos.find(ordem.veiculo_id).placa %></td>
                <td><%= ordem.status %></td>
                <% if ordem.equipe_id != nil %>
                    <td><%= @equipes.find(ordem.equipe_id).nome %></td>
                <% else %>
                    <td></td>
                <% end %>
                <td>
                    <%= link_to ordem, class: "text-decoration-none" do %>
                        <i class="bi bi-eye-fill fs-4 link-dark"></i>
                    <% end %>
                    <%= link_to edit_ordem_path(ordem), class: "text-decoration-none" do %>
                        <i class="bi bi-pen-fill fs-4 link-dark"></i>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/ordems/new.html.erb
<h1>Nova Ordem de Serviço</h1>

<%= render "form", ordem: @ordem %>

app/views/ordems/show.html.erb
<%= link_to "Voltar", ordems_path %>

<h2>Veículo: <%= @veiculo.placa %></h2>

<p>Equipe: <%= @equipe.nome %></p>

<hr>

<p>Emissão: <%= @ordem.dataEmissao %></p>

<p>Conclusão: <%= @ordem.dataConclusao %></p>

<h3>Partes</h3>

<table class="table table-bordered table-hover table-striped mt-3">
    <thead>
        <tr>
            <th class="col">#</th>
            <th class="col">Nome</th>
            <th class="col">Modelo</th>
            <th class="col">Valor</th>
            <th class="col">Ações</th>
        </tr>
    </thead>
    <tbody>
        <% @partes.each do |parte| %>
            <tr>
                <td><%= parte.id %></td>
                <td><%= parte.nome %></td>
                <td><%= parte.modelo %></td>
                <td><%= parte.valor %></td>
                <td>
                    <%= link_to parte, class: "text-decoration-none" do %>
                        <i class="bi bi-eye-fill fs-4 link-dark"></i>
                    <% end %>
                    <%= link_to edit_parte_path(parte), class: "text-decoration-none" do %>
                        <i class="bi bi-pen-fill fs-4 link-dark"></i>
                    <% end %>
                </td>

            </tr>
        <% end %>
    </tbody>
</table>

<h3>Serviços</h3>
<table class="table table-bordered table-hover table-striped mt-3">
    <thead>
        <tr>
            <th class="col">#</th>
            <th class="col">Nome</th>
            <th class="col">Valor</th>
            <th class="col">Ações</th>
        </tr>
    </thead>
    <tbody>
        <% @servicos.each do |servico| %>
            <tr>
                <td><%= servico.id %></td>
                <td><%= servico.nome %></td>
                <td><%= servico.valor %></td>
                <td>
                    <%= link_to servico, class: "text-decoration-none" do %>
                        <i class="bi bi-eye-fill fs-4 link-dark"></i>
                    <% end %>
                    <%= link_to edit_servico_path(servico), class: "text-decoration-none" do %>
                        <i class="bi bi-pen-fill fs-4 link-dark"></i>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/partes/_form.html.erb
<%= form_with model: parte, class:"col-10" do |form| %>
    <div>
        <%= form.label :nome, class:"form-label mt-2" %><br>
        <%= form.text_field :nome, class:"form-control" %>
        <% parte.errors.full_messages_for(:nome).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :descricao, class:"form-label mt-2" %><br>
        <%= form.text_field :descricao, class:"form-control" %>
        <% parte.errors.full_messages_for(:descricao).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :modelo, class:"form-label mt-2" %><br>
        <%= form.text_field :modelo, class:"form-control" %>
        <% parte.errors.full_messages_for(:modelo).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :valor, class:"form-label mt-2" %><br>
        <%= form.text_field :valor, class:"form-control" %>
        <% parte.errors.full_messages_for(:valor).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div class="mt-3">
        <%= form.submit %>
    </div>
<% end %>

app/views/partes/edit.html.erb
<h1>Editar parte</h1>

<%= render "form", parte: @parte %>

app/views/partes/index.html.erb
<h1>Partes</h1>

<%= link_to new_parte_path, class: "text-decoration-none fs-4" do %>
    <div>
        <i class="bi bi-plus-circle"></i> Novo
    </div>
<% end %>

<table class="table table-bordered table-hover table-striped mt-3">
    <thead>
        <tr>
            <th class="col">#</th>
            <th class="col">Nome</th>
            <th class="col">Modelo</th>
            <th class="col">Valor</th>
            <th class="col">Ações</th>
        </tr>
    </thead>
    <tbody>
        <% @partes.each do |parte| %>
            <tr>
                <td><%= parte.id %></td>
                <td><%= parte.nome %></td>
                <td><%= parte.modelo %></td>
                <td><%= parte.valor %></td>
                <td>
                    <%= link_to parte, class: "text-decoration-none" do %>
                        <i class="bi bi-eye-fill fs-4 link-dark"></i>
                    <% end %>
                    <%= link_to edit_parte_path(parte), class: "text-decoration-none" do %>
                        <i class="bi bi-pen-fill fs-4 link-dark"></i>
                    <% end %>
                </td>

            </tr>
        <% end %>
    </tbody>
</table>

app/views/partes/new.html.erb
<h1>Nova parte</h1>

<%= render "form", parte: @parte %>

app/views/partes/show.html.erb
<%= link_to "Voltar", partes_path %>

<h1><%= @parte.nome %></h1>

<p><%= @parte.descricao %></p>

<p>Valor: <%= @parte.valor %></p>