config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :ordems, :partes, :equipes, :mecanicos, :servicos

  resources :clientes do
    resources :veiculos
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "ordems#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many :veiculos, dependent: :destroy

  validates :nome, presence: true
  validates :endereco, presence: true
  validates :telefone, presence: true
end

app/models/equipe.rb
class Equipe < ApplicationRecord
  has_many :mecanicos

  validates :nome, presence: true

  def numIntegrantes?
    Mecanico.where(equipe_id:id).count
  end
end

app/models/mecanico.rb
class Mecanico < ApplicationRecord
  validates :nome, presence: true
  validates :endereco, presence: true
  validates :especialidade, presence: true
end

app/models/ordem.rb
class Ordem < ApplicationRecord

  STATUS_VALIDOS = ['Aberto', 'Em andamento', 'Pausado', 'Finalizado']

  validates :problema, presence: true
  validates :dataEmissao, presence: true
  validates :veiculo_id, presence: true
  validates :status, presence: true, inclusion: { in: STATUS_VALIDOS }



end

app/models/ordems_partes.rb
class Ordems_partes < ApplicationRecord
  belongs_to :ordem, :parte
end

app/models/ordems_servicos.rb
class Ordems_servicos < ApplicationRecord
  belongs_to :servico, :ordem
end

app/models/parte.rb
class Parte < ApplicationRecord

  validates :nome, presence: true
  validates :descricao, presence: true
  validates :valor, presence: true



end

app/models/servico.rb
class Servico < ApplicationRecord

  validates :nome, presence: true
  validates :descricao, presence: true
  validates :valor, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
  belongs_to :cliente

  validates :placa, presence: true
  validates :marca, presence: true
  validates :modelo, presence: true
  validates :ano, presence: true
  validates :cor, presence: true
  validates :descricao, presence: true
end

app/controllers/equipes_controller.rb
class EquipesController < ApplicationController
  before_action :authenticate_user!
  def index
    @equipes = Equipe.all
  end

  def show
    @equipe = Equipe.find(params[:id])
    @integrantes = Mecanico.all
  end

  def new
    @equipe = Equipe.new
  end

  def create
    @equipe = Equipe.new(equipe_params)

    if @equipe.save
      redirect_to @equipe
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @integrantes = params[:integrantes]
    @integrantes.each do |integrante|
      if(integrante != "")
        @mecanico = Mecanico.find(integrante)
        @mecanico.equipe_id = params[:equipe_id]
        @mecanico.save
      end
    end
    redirect_to equipe_path(params[:equipe_id])
  end

  private
    def equipe_params
      params.require(:equipe).permit(:nome)
    end


end

app/controllers/ordems_controller.rb
class OrdemsController < ApplicationController
  before_action :authenticate_user!
  before_action :carregarDependencias, only: [:new, :index, :edit]

  def index
    @ordems = Ordem.all
  end

  def show
    @ordem = Ordem.find(params[:id])
    @veiculo = Veiculo.find(@ordem.veiculo_id)
    @equipe = Equipe.find(@ordem.equipe_id)
    @partes = []
    @servicos = []
  end

  def new
    @novo = true
    @ordem = Ordem.new
  end

  def create

    @ordem = Ordem.new(ordem_params)

    if @ordem.save
      redirect_to @ordem
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @novo = false
    @ordem = Ordem.find(params[:id])
  end

  def update
    @ordem = Ordem.find(params[:id])

    if @ordem.update(ordem_params)
      redirect_to @ordem
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def ordem_params
      params.require(:ordem).permit(:dataEmissao, :problema, :equipe_id, :status, :veiculo_id, :partes, :servicos)
    end

    def carregarDependencias
      @veiculos = Veiculo.all
      @equipes = Equipe.all
      @partes = Parte.all
      @servicos = Servico.all
    end
end

app/controllers/partes_controller.rb
class PartesController < ApplicationController
  before_action :authenticate_user!
  def index
    @partes = Parte.all
  end

  def show
    @parte = Parte.find(params[:id])
  end

  def new
    @parte = Parte.new
  end

  def create
    @parte = Parte.new(parte_params)

    if @parte.save
      redirect_to @parte
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @parte = Parte.find(params[:id])
  end

  def update
    @parte = Parte.find(params[:id])

    if @parte.update(ordem_params)
      redirect_to @parte
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def parte_params
      params.require(:parte).permit(:nome, :descricao, :modelo, :valor)
    end
end

app/controllers/servicos_controller.rb
class ServicosController < ApplicationController
  before_action :authenticate_user!
  def index
    @servicos = Servico.all
  end

  def show
    @servico = Servico.find(params[:id])
  end

  def new
    @servico = Servico.new
  end

  def create
    @servico = Servico.new(servico_params)

    if @servico.save
      redirect_to @servico
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @servico = Servico.find(params[:id])
  end

  def update
    @servico = Servico.find(params[:id])

    if @servico.update(ordem_params)
      redirect_to @servico
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def servico_params
      params.require(:servico).permit(:nome, :descricao, :valor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/equipes_helper.rb
module EquipesHelper
end

app/helpers/mecanicos_helper.rb
module MecanicosHelper
end

app/helpers/ordems_helper.rb
module OrdemsHelper
end

app/helpers/partes_helper.rb
module PartesHelper
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/servicos/_form.html.erb
<%= form_with model: servico, class:"col-10" do |form| %>
    <div>
        <%= form.label :nome, class:"form-label mt-2" %><br>
        <%= form.text_field :nome, class:"form-control" %>
        <% servico.errors.full_messages_for(:nome).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :descricao, class:"form-label mt-2" %><br>
        <%= form.text_field :descricao, class:"form-control" %>
        <% servico.errors.full_messages_for(:descricao).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :valor, class:"form-label mt-2" %><br>
        <%= form.text_field :valor, class:"form-control" %>
        <% servico.errors.full_messages_for(:valor).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div class="mt-3">
        <%= form.submit %>
    </div>
<% end %>

app/views/servicos/edit.html.erb
<h1>Novo serviço</h1>

<%= render "form", servico: @servico %>

app/views/servicos/index.html.erb
<h1>Serviços</h1>

<%= link_to new_servico_path, class: "text-decoration-none fs-4" do %>
    <div>
        <i class="bi bi-plus-circle"></i> Novo
    </div>
<% end %>

<table class="table table-bordered table-hover table-striped mt-3">
    <thead>
        <tr>
            <th class="col">#</th>
            <th class="col">Nome</th>
            <th class="col">Valor</th>
            <th class="col">Ações</th>
        </tr>
    </thead>
    <tbody>
        <% @servicos.each do |servico| %>
            <tr>
                <td><%= servico.id %></td>
                <td><%= servico.nome %></td>
                <td><%= servico.valor %></td>
                <td>
                    <%= link_to servico, class: "text-decoration-none" do %>
                        <i class="bi bi-eye-fill fs-4 link-dark"></i>
                    <% end %>
                    <%= link_to edit_servico_path(servico), class: "text-decoration-none" do %>
                        <i class="bi bi-pen-fill fs-4 link-dark"></i>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/servicos/new.html.erb
<h1>Novo serviço</h1>

<%= render "form", servico: @servico %>

app/views/servicos/show.html.erb
<%= link_to "Voltar", servicos_path %>

<h1><%= @servico.nome %></h1>

<p><%= @servico.descricao %></p>

<p>Valor: <%= @servico.valor %></p>