config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :ordems, :partes, :equipes, :mecanicos, :servicos

  resources :clientes do
    resources :veiculos
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "ordems#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many :veiculos, dependent: :destroy

  validates :nome, presence: true
  validates :endereco, presence: true
  validates :telefone, presence: true
end

app/models/equipe.rb
class Equipe < ApplicationRecord
  has_many :mecanicos

  validates :nome, presence: true

  def numIntegrantes?
    Mecanico.where(equipe_id:id).count
  end
end

app/models/mecanico.rb
class Mecanico < ApplicationRecord
  validates :nome, presence: true
  validates :endereco, presence: true
  validates :especialidade, presence: true
end

app/models/ordem.rb
class Ordem < ApplicationRecord

  STATUS_VALIDOS = ['Aberto', 'Em andamento', 'Pausado', 'Finalizado']

  validates :problema, presence: true
  validates :dataEmissao, presence: true
  validates :veiculo_id, presence: true
  validates :status, presence: true, inclusion: { in: STATUS_VALIDOS }



end

app/models/ordems_partes.rb
class Ordems_partes < ApplicationRecord
  belongs_to :ordem, :parte
end

app/models/ordems_servicos.rb
class Ordems_servicos < ApplicationRecord
  belongs_to :servico, :ordem
end

app/models/parte.rb
class Parte < ApplicationRecord

  validates :nome, presence: true
  validates :descricao, presence: true
  validates :valor, presence: true



end

app/models/servico.rb
class Servico < ApplicationRecord

  validates :nome, presence: true
  validates :descricao, presence: true
  validates :valor, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
  belongs_to :cliente

  validates :placa, presence: true
  validates :marca, presence: true
  validates :modelo, presence: true
  validates :ano, presence: true
  validates :cor, presence: true
  validates :descricao, presence: true
end

app/controllers/ordems_controller.rb
class OrdemsController < ApplicationController
  before_action :authenticate_user!
  before_action :carregarDependencias, only: [:new, :index, :edit]

  def index
    @ordems = Ordem.all
  end

  def show
    @ordem = Ordem.find(params[:id])
    @veiculo = Veiculo.find(@ordem.veiculo_id)
    @equipe = Equipe.find(@ordem.equipe_id)
    @partes = []
    @servicos = []
  end

  def new
    @novo = true
    @ordem = Ordem.new
  end

  def create

    @ordem = Ordem.new(ordem_params)

    if @ordem.save
      redirect_to @ordem
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @novo = false
    @ordem = Ordem.find(params[:id])
  end

  def update
    @ordem = Ordem.find(params[:id])

    if @ordem.update(ordem_params)
      redirect_to @ordem
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def ordem_params
      params.require(:ordem).permit(:dataEmissao, :problema, :equipe_id, :status, :veiculo_id, :partes, :servicos)
    end

    def carregarDependencias
      @veiculos = Veiculo.all
      @equipes = Equipe.all
      @partes = Parte.all
      @servicos = Servico.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/equipes_helper.rb
module EquipesHelper
end

app/helpers/mecanicos_helper.rb
module MecanicosHelper
end

app/helpers/ordems_helper.rb
module OrdemsHelper
end

app/helpers/partes_helper.rb
module PartesHelper
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/layouts/_nav.html.erb
<nav class="mt-5">
    <ul class="nav flex-column">
        <li class="nav-item">
            <%= link_to "Ordens de Serviço", ordems_path, class: 'text-decoration-none nav-link active' %>
        </li>
        <li class="nav-item">
            <%= link_to "Clientes", clientes_path, class: 'text-decoration-none nav-link active' %>
        </li>
        <li class="nav-item">
            <%= link_to "Mecanicos", mecanicos_path, class: 'text-decoration-none nav-link active' %>
        </li>
        <li class="nav-item">
            <%= link_to "Equipes", equipes_path, class: 'text-decoration-none nav-link active' %>
        </li>
        <li class="nav-item">
            <%= link_to "Partes", partes_path, class: 'text-decoration-none nav-link active' %>
        </li>
        <li class="nav-item">
            <%= link_to "Serviços", servicos_path, class: 'text-decoration-none nav-link active' %>
        </li>
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= button_to("Log Out", destroy_user_session_path, {method: :delete, style:"border:0px;background-color:#fff;", class: 'text-decoration-none nav-link active'}) %>
            </li>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <title>OrdemDeServico</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
  
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-2">
          <p class="alert"><%= alert %></p>
          <%= render "layouts/nav" %>
        </div>
        <div class="col-10">
          <p class="notice"><%= notice %></p>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>